# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets

from APP.GUI.utils.views import AccountsPage, ChatPage, SettingsPage, OrderPage, ProgressPage
from settings import images_folder


class Ui_MainWindow(object):
    def setupUi(self, MainWindow: QtWidgets.QMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1056, 858)
        MainWindow.setStyleSheet("margin: 0px;\n"
"padding: 0px;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 600))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        
        # NOTE страница для информирования пока что в этой функции
        
        self.tab_start = QtWidgets.QWidget()
        self.tab_start.setObjectName("tab_start")
        self.title = QtWidgets.QLabel(self.tab_start)
        self.title.setGeometry(QtCore.QRect(60, 30, 781, 31))
        self.title.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setWordWrap(False)
        self.title.setObjectName("title")
        self.tabWidget.addTab(self.tab_start, "")

        self.tab = OrderPage(MainWindow, _translate)

        self.tabWidget.addTab(self.tab, "")
        
        self.tab_progress = ProgressPage()
                
        self.tabWidget.addTab(self.tab_progress, "")
        
        self.tab_all_accs = AccountsPage()

        self.tabWidget.addTab(self.tab_all_accs, "")
        
        self.tab_settings = SettingsPage()
        
        self.tabWidget.addTab(self.tab_settings, "")
        
        self.chat_page = ChatPage()
        
        self.tabWidget.addTab(self.chat_page, "")
        
        # NOTE страница для работы с базами
        
        # NOTE страница для общения с пользователями

        self.horizontalLayout_14.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow, _translate)
        self.tabWidget.setCurrentIndex(1) # TODO тут тоже нужно настроить стартовый индекс

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        return self

    def retranslateUi(self, MainWindow: QtWidgets.QMainWindow, _translate):
        MainWindow.setWindowTitle(_translate("MainWindow", "TG Spammer V{}".format(os.getenv('VERSION'))))
        MainWindow.setWindowIcon(
            QtGui.QIcon(
                os.path.join(
                    images_folder,
                    "ava_logo.png"
                )
            )
        )
        self.title.setText(_translate("MainWindow", "TG Spammer V{}".format(os.getenv('VERSION'))))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_start), _translate("MainWindow", "Hello Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Запуск Аккаунтов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_progress), _translate("MainWindow", "Пргресс работы аккаунтов"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_all_accs), _translate("MainWindow", "Все Аккаунты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("MainWindow", "Настройки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chat_page), _translate("MainWindow", "Чат"))